# The name of the application we're trying to generate
TARGET = mazegen

SRC = list.c mazegen.c graph.c
HDR = list.h graph.h

# The following three lines can be used to automatically generate the SRC, HDR
# and OBJ variables instead of doing it statically as above
OBJ := $(SRC:.c=.o)

# These variables are used by make in all of it's automatic rules.
# Specifically, use CFLAGS for the "-g -O0" option if you want to do debugging,
# and LDFLAGS for the "-lm" option if you are using the math library.
CC = gcc
CFLAGS = -W -Wall -ansi -g -O0 -D_XOPEN_SOURCE=500
LDFLAGS = -lm -lncurses

# Default target, builds your entire project.  Simply running 'make' will run
# this target
$(TARGET) : $(OBJ)
	$(CC) -o $@ $(OBJ) $(LDFLAGS)

# This generates the dependencies between your various .c and .h files, using
# the c compiler's -MM option.
depend : $(SRC) mazegen.c $(HDR)
	$(CC) $(CFLAGS) -MM $(SRC) > depend

# This includes the dependencies made with the previous rule, and in fact forces
# them to be generated.
-include depend

# The rules below clean up any files generated by the make process.  clean
# should be run to clear out the temporary files, and clobber should be run if
# you modify your makefile (for example to change the CFLAGS or LDFLAGS options)
# so that you can get a clean recompile.
.PHONY : all test clean clobber

all : $(TARGET)

clean :
	-rm -f $(OBJ) $(TOBJ) depend

clobber :
	-rm -f $(TARGET) $(OBJ) $(TOBJ) depend
	-rm -f *~ 
